complexity:
  LongMethod:
    threshold: 100
    ignoreAnnotated: [ 'Composable', 'OptIn' ]
  CyclomaticComplexMethod:
    threshold: 40
    ignoreAnnotated: [ 'Composable' ]
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  ComplexCondition:
    threshold: 7

performance:
  SpreadOperator:
    active: false

style:
  MagicNumber:
    active: false
    ignoreAnnotated: [ 'AllowMagicNumber' ]
  ForbiddenComment:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview', 'ComponentPreview', 'DevicePreview' ]
  ThrowsCount:
    active: false
  ReturnCount:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  MaxLineLength:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  MatchingDeclarationName:
    active: false
  VariableNaming:
    active: false
  PackageNaming:
    packagePattern: '[a-z]+(\._?[_?A-Za-z0-9]*)*'